services:
  - type: web
    name: crypto-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-monitor-db
          property: connectionString

databases:
  - name: crypto-monitor-db
    ipAllowList: []
