services:
  # Web service
  - type: web
    name: crypto-portfolio-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app()
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-portfolio-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: crypto-portfolio-redis
          property: connectionString

  # Redis service
  - type: redis
    name: crypto-portfolio-redis
    ipAllowList: []
    plan: free

databases:
  - name: crypto-portfolio-db
    databaseName: crypto_portfolio
    user: crypto_portfolio_user
    plan: free
