database:
  host: localhost
  port: 5001
  user: postgres
  password: ""  # Leave empty for no password
  database_name: monitoring_db

alerting:
  thresholds:
    cpu_usage: 80
    memory_usage: 75
    query_response_time: 2.0

visualization:
  output_format: png
  report_interval: daily
  show_trends: true

